---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	extract_erd(extract_erd)
	convert_erd(convert_erd)
	validate_erd(validate_erd)
	__end__([<p>__end__</p>]):::last
	__start__ --> extract_erd;
	convert_erd --> validate_erd;
	extract_erd --> convert_erd;
	validate_erd --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
